// TDD-red spec for "embedded/CJK fonts on builder-created text fields" (scope A).
// These tests describe the target behavior; they fail until the feature lands:
//   - addTextField({ font: <embedded PdfFont> }) on plain + multiline text fields
//   - CID/Type0 appearance generated by the create path
//   - subsetting is field-aware (subset: true just works)
//   - comb / dropdown / listbox reject an embedded font
//   - re-filling an embedded-font field via the form API throws (scope B seam)
import { expect, test } from "bun:test";
import { PdfDocument, PdfError, PageSizes } from "../src/index.ts";
import { readFileSync } from "node:fs";

const FONT = new Uint8Array(readFileSync("tests/fixtures/fonts/NotoSans-Regular.subset.ttf"));

// A value the NotoSans subset fixture has glyphs for (see font-embedding.test.ts).
const VALUE = "Héllo 日本語";

test("plain text field renders its value in an embedded font and round-trips", async () => {
  const doc = await PdfDocument.create();
  const font = await doc.embedFont(FONT);
  doc.addPage(PageSizes.A4);
  doc.createForm().addTextField("name", {
    page: 0,
    x: 50,
    y: 700,
    width: 240,
    height: 20,
    value: VALUE,
    font,
  });

  const out = await doc.save();
  expect(out.length).toBeGreaterThan(1000);

  const reloaded = await PdfDocument.load(out);
  const field = reloaded.getForm().getField("name");
  expect(field).toBeDefined();
  expect(field!.type).toBe("text");
  expect(field!.value).toBe(VALUE);
});

test("multiline text field with an embedded font saves and round-trips", async () => {
  const doc = await PdfDocument.create();
  const font = await doc.embedFont(FONT);
  doc.addPage(PageSizes.A4);
  doc.createForm().addTextField("bio", {
    page: 0,
    x: 50,
    y: 500,
    width: 200,
    height: 120,
    multiline: true,
    value: "日本語 のテキスト that should wrap across several lines in the box",
    font,
  });

  const out = await doc.save();
  const reloaded = await PdfDocument.load(out);
  const field = reloaded.getForm().getField("bio");
  expect(field).toBeDefined();
  expect(field!.type).toBe("text");
});

test("subsetting is field-aware: a font used only by a field embeds and saves", async () => {
  const doc = await PdfDocument.create();
  const font = await doc.embedFont(FONT); // default subset: true, never drawn
  doc.addPage(PageSizes.A4);
  doc.createForm().addTextField("only", {
    page: 0,
    x: 50,
    y: 700,
    width: 200,
    height: 20,
    value: VALUE,
    font,
  });

  // Must produce a valid PDF (goes through qpdf-validate elsewhere) with the
  // field's glyphs embedded — no blank/.notdef output.
  const out = await doc.save();
  expect(out.length).toBeGreaterThan(1000);
  const reloaded = await PdfDocument.load(out);
  expect(reloaded.getForm().getField("only")!.value).toBe(VALUE);
});

test("comb field rejects an embedded font", async () => {
  const doc = await PdfDocument.create();
  const font = await doc.embedFont(FONT);
  doc.addPage(PageSizes.A4);
  expect(() =>
    doc.createForm().addTextField("code", {
      page: 0,
      x: 50,
      y: 700,
      width: 200,
      height: 20,
      comb: true,
      maxLength: 6,
      font,
    }),
  ).toThrow(/plain and multiline text fields only/);
});

test("dropdown rejects an embedded font", async () => {
  const doc = await PdfDocument.create();
  const font = await doc.embedFont(FONT);
  doc.addPage(PageSizes.A4);
  expect(() =>
    // `font` on choice fields is typed StandardFonts; cast exercises the runtime guard.
    doc.createForm().addDropdown("pick", {
      page: 0,
      x: 50,
      y: 700,
      width: 200,
      height: 20,
      options: ["a", "b"],
      font: font as unknown as never,
    }),
  ).toThrow(/plain and multiline text fields only/);
});

test("re-filling an embedded-font field via the form API throws", async () => {
  const doc = await PdfDocument.create();
  const font = await doc.embedFont(FONT);
  doc.addPage(PageSizes.A4);
  doc.createForm().addTextField("name", {
    page: 0,
    x: 50,
    y: 700,
    width: 240,
    height: 20,
    value: VALUE,
    font,
  });

  // getForm() materializes the created doc; setText queues a fill op that would
  // mis-encode the Type0 font. The fill path must reject at save().
  doc.getForm().getTextField("name").setText("花子");
  await expect(doc.save()).rejects.toThrow(/not yet supported/);
});

test("standard-14 fields are unaffected by the widened font option", async () => {
  const doc = await PdfDocument.create();
  doc.addPage(PageSizes.A4);
  doc.createForm().addTextField("plain", {
    page: 0,
    x: 50,
    y: 700,
    width: 200,
    height: 20,
    value: "ASCII only",
  });
  const out = await doc.save();
  const reloaded = await PdfDocument.load(out);
  expect(reloaded.getForm().getField("plain")!.value).toBe("ASCII only");
});
