// Behavioral tests ported from pypdf's test suite (https://github.com/py-pdf/pypdf),
// adapted to the better-pdf API. Fixtures under fixtures/pypdf/ are copied from
// pypdf's `resources/` folder (BSD-3-Clause; see fixtures/pypdf/LICENSE.pypdf).
//
// The encryption fixtures (encryption/r{2..6}-*.pdf) were generated by pypdf with
// qpdf --encrypt; the exact commands live in pypdf's tests/test_encryption.py.
// Where pypdf asserts exact appearance-operator byte strings, we port the observable
// *behavior* (field flags, round-tripped values) rather than the literal bytes,
// since better-pdf emits its own appearance streams.
import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { PdfDocument } from "../src/index.ts";
import { IncorrectPasswordError, PdfError } from "../src/core/errors.ts";

const DIR = join(import.meta.dir, "fixtures/pypdf");
const bytes = (name: string) => new Uint8Array(readFileSync(join(DIR, name)));
const enc = (s: string) => new TextEncoder().encode(s);

// pypdf's `is not "/Off"` truthiness for on/off widget states.
const isChecked = (value: string | null) => value != null && value !== "" && value !== "Off";

// ---------------------------------------------------------------------------
// Tier 1 — Encryption matrix (pypdf tests/test_encryption.py)
// ---------------------------------------------------------------------------
describe("encryption matrix (pypdf resources/encryption)", () => {
  // Every fixture decrypts to the same one-page document whose metadata author
  // is "cheng". `password` below is a password that must authenticate the file:
  // "" for empty-password files, "asdfzxcv" for the user/owner-password files.
  const cases: Array<{ file: string; password: string; note: string }> = [
    { file: "r2-empty-password.pdf", password: "", note: "R2 RC4-40, no password" },
    { file: "r3-empty-password.pdf", password: "", note: "R3 RC4-128, no password" },
    { file: "r2-user-password.pdf", password: "asdfzxcv", note: "R2 user password" },
    { file: "r2-owner-password.pdf", password: "asdfzxcv", note: "R2 owner password" },
    { file: "r3-user-password.pdf", password: "asdfzxcv", note: "R3 user password" },
    { file: "r4-user-password.pdf", password: "asdfzxcv", note: "R4/V4 RC4 user password" },
    { file: "r4-owner-password.pdf", password: "asdfzxcv", note: "R4/V4 RC4 owner password" },
    { file: "r4-aes-user-password.pdf", password: "asdfzxcv", note: "R4/V4 AESV2 user password" },
    { file: "r5-empty-password.pdf", password: "", note: "R5 AES-256, no password" },
    { file: "r5-user-password.pdf", password: "asdfzxcv", note: "R5 AES-256 user password" },
    { file: "r5-owner-password.pdf", password: "asdfzxcv", note: "R5 AES-256 owner password" },
    { file: "r6-empty-password.pdf", password: "", note: "R6 AES-256, no password" },
    { file: "r6-user-password.pdf", password: "asdfzxcv", note: "R6 AES-256 user password" },
    { file: "r6-owner-password.pdf", password: "asdfzxcv", note: "R6 AES-256 owner password" },
  ];

  for (const { file, password, note } of cases) {
    test(`decrypts ${file} (${note})`, async () => {
      const doc = await PdfDocument.load(bytes(`encryption/${file}`), { password });
      expect(doc.getPageCount()).toBe(1);
      const meta = await doc.getMetadata();
      expect(meta.author).toBe("cheng");
    });
  }

  test("unencrypted.pdf loads without a password", async () => {
    const doc = await PdfDocument.load(bytes("encryption/unencrypted.pdf"));
    expect(doc.getPageCount()).toBe(1);
  });

  // Use r6-both-passwords.pdf: it has a non-empty user *and* owner password, so
  // a wrong password authenticates against neither. (r6-user-password.pdf has an
  // empty owner password, which any string opens as owner.)
  test("wrong password throws IncorrectPasswordError (R6 AES-256)", async () => {
    await expect(
      PdfDocument.load(bytes("encryption/r6-both-passwords.pdf"), { password: "nope" }),
    ).rejects.toThrow(IncorrectPasswordError);
  });

  // pypdf test_pdf_with_both_passwords: both the user ("foo") and owner ("bar")
  // password authenticate the same R6 file.
  test("r6-both-passwords.pdf: user password (foo) authenticates", async () => {
    const doc = await PdfDocument.load(bytes("encryption/r6-both-passwords.pdf"), { password: "foo" });
    expect(doc.getPageCount()).toBe(1);
  });
  test("r6-both-passwords.pdf: owner password (bar) authenticates", async () => {
    const doc = await PdfDocument.load(bytes("encryption/r6-both-passwords.pdf"), { password: "bar" });
    expect(doc.getPageCount()).toBe(1);
  });

  // pypdf test_read_page_from_encrypted_file_aes_256 (regression for issue 327).
  test("crazyones-encrypted-256.pdf opens and exposes its page", async () => {
    const doc = await PdfDocument.load(bytes("crazyones-encrypted-256.pdf"), { password: "password" });
    expect(doc.getPageCount()).toBe(1);
    expect(doc.getPage(0).width).toBeGreaterThan(0);
  });

  // pypdf test_aesv2_without_length_in_encrypt_dict: a V4 (AES-128) file that
  // omits /Length from the main /Encrypt dict is fixed at 128-bit by spec. lopdf
  // 0.41 defaults to 40 bits and fails to authenticate; better-pdf injects
  // /Length 128 and retries so the file decrypts.
  test("r4-aes-v2-no-key-length.pdf decrypts with empty password", async () => {
    const doc = await PdfDocument.load(bytes("encryption/r4-aes-v2-no-key-length.pdf"), { password: "" });
    expect(doc.getPageCount()).toBe(1);
  });
});

// pypdf reader.is_encrypted — a password-free predicate so callers can branch.
describe("PdfDocument.isEncrypted (pypdf reader.is_encrypted)", () => {
  test("reports true for encrypted files, false for plain", async () => {
    expect(await PdfDocument.isEncrypted(bytes("encryption/r2-empty-password.pdf"))).toBe(true);
    expect(await PdfDocument.isEncrypted(bytes("encryption/r6-both-passwords.pdf"))).toBe(true);
    expect(
      await PdfDocument.isEncrypted(bytes("encryption/r4-aes-v2-no-key-length.pdf")),
    ).toBe(true);
    expect(await PdfDocument.isEncrypted(bytes("encryption/unencrypted.pdf"))).toBe(false);
    expect(await PdfDocument.isEncrypted(bytes("form.pdf"))).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Tier 2 — Form field value semantics (pypdf test_reader.py / test_writer.py)
// ---------------------------------------------------------------------------
describe("reading form field values across producers (pypdf test_get_form)", () => {
  const cases: Array<{ file: string; value: string }> = [
    { file: "form.pdf", value: "" },
    { file: "form_acrobatReader.pdf", value: "Bar" },
    { file: "form_evince.pdf", value: "bar" },
  ];
  for (const { file, value } of cases) {
    test(`${file}: text field "foo" reads "${value}"`, async () => {
      const doc = await PdfDocument.load(bytes(file));
      const foo = doc.getForm().getField("foo");
      expect(foo?.type).toBe("text");
      expect(foo?.value ?? "").toBe(value);
    });
  }
});

describe("FormTestFromOo.pdf field metadata (pypdf test_update_form_fields)", () => {
  const form = async () => (await PdfDocument.load(bytes("FormTestFromOo.pdf"))).getForm();

  test("checkbox exposes its on-state and starts Off", async () => {
    const cb = (await form()).getField("CheckBox1");
    expect(cb?.type).toBe("checkbox");
    expect(cb?.states).toEqual(["Yes"]);
    expect(isChecked(cb?.value ?? null)).toBe(false);
  });

  test("radio group enumerates its export states", async () => {
    const rg = (await form()).getField("RadioGroup1");
    expect(rg?.type).toBe("radio");
    expect(rg?.states).toEqual(["1", "2", "3"]);
  });

  test("single-select and multi-select list boxes expose options", async () => {
    const single = (await form()).getField("Liste1");
    expect(single?.type).toBe("listbox");
    expect(single?.multiSelect).toBe(false);
    expect(single?.options).toEqual(["Liste1", "Liste2", "Liste3"]);

    const multi = (await form()).getField("Liste2");
    expect(multi?.multiSelect).toBe(true);
    expect(multi?.options).toEqual(["Lst1", "Lst2", "Lst3", "Lst4"]);
  });

  test("combo and drop-list fields expose options", async () => {
    const combo = (await form()).getField("Combo1");
    expect(combo?.type).toBe("dropdown");
    expect(combo?.options).toEqual(["combo Line 1", "combo Line 2", "combo Line 3"]);
  });
});

describe("filling FormTestFromOo.pdf round-trips values (pypdf test_update_form_fields)", () => {
  test("checkbox, radio, multi-select, and combo persist through save/reload", async () => {
    const doc = await PdfDocument.load(bytes("FormTestFromOo.pdf"));
    const form = doc.getForm();
    form.getCheckBox("CheckBox1").check();
    form.getRadioGroup("RadioGroup1").select("2");
    form.getListBox("Liste2").selectMultiple(["Lst1", "Lst3"]);
    form.getDropdown("Combo1").select("combo Line 2");

    const out = await doc.save();
    const reloaded = (await PdfDocument.load(out)).getForm();
    expect(reloaded.getField("CheckBox1")?.value).toBe("Yes");
    expect(reloaded.getField("RadioGroup1")?.value).toBe("2");
    expect(reloaded.getField("Combo1")?.value).toBe("combo Line 2");
    // multi-select value re-reads as the selected export values.
    const multi = reloaded.getField("Liste2")?.value ?? "";
    expect(multi).toContain("Lst1");
    expect(multi).toContain("Lst3");
  });

  // pypdf test_form_button__v_value_should_be_name_object: a set button /V must
  // serialize as a name object (`/V /Yes`), never a string (`/V (Yes)`).
  test("checked button serializes /V as a name object, not a string", async () => {
    const doc = await PdfDocument.load(bytes("FormTestFromOo.pdf"));
    doc.getForm().getCheckBox("CheckBox1").check();
    const out = await doc.save();
    const raw = Buffer.from(out).toString("latin1");
    expect(raw).toMatch(/\/V\s*\/Yes/);
    expect(raw).not.toMatch(/\/V\s*\(Yes\)/);
  });
});

// ---------------------------------------------------------------------------
// Tier 3 — Appearance / variable-text flags (pypdf test_appearance_stream.py)
//   pypdf asserts exact operator bytes; we port the field-level flag semantics
//   that drive comb layout and auto-size, plus the fill round-trip.
// ---------------------------------------------------------------------------
describe("variable-text field flags (pypdf comb / auto-size behavior)", () => {
  const FICHA = join(
    import.meta.dir,
    "fixtures/Discapacidad/Form.-D.P.-2.4.1-Ficha-personal.pdf",
  );
  const fichaForm = async () =>
    (await PdfDocument.load(new Uint8Array(readFileSync(FICHA)))).getForm();

  test("auto-size text fields report fontSize 0 (the '0 Tf' convention)", async () => {
    const autosize = (await fichaForm()).getFields().filter((f) => f.fontSize === 0);
    expect(autosize.length).toBeGreaterThan(0);
  });

  test("filling an auto-size text field round-trips its value", async () => {
    const doc = await PdfDocument.load(new Uint8Array(readFileSync(FICHA)));
    const target = doc.getForm().getFields().find((f) => f.type === "text" && f.fontSize === 0)!;
    doc.getForm().getTextField(target.name).setText("HELLO");
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getForm().getField(target.name)?.value).toBe("HELLO");
  });

  test("non-comb fields report comb=false (FormTestFromOo)", async () => {
    const form = (await PdfDocument.load(bytes("FormTestFromOo.pdf"))).getForm();
    expect(form.getField("Text1")?.comb).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// Tier 4 — Malformed-PDF recovery (pypdf test_reader.py)
//   Ported as inline byte fixtures to mirror pypdf's non-strict recovery.
// ---------------------------------------------------------------------------
describe("malformed-PDF recovery (pypdf test_reader.py)", () => {
  const MIN = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
xref
0 4
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
190
%%EOF`;

  test("baseline fixture loads (sanity)", async () => {
    const doc = await PdfDocument.load(enc(MIN));
    expect(doc.getPageCount()).toBe(1);
  });

  // pypdf test_broken_file_header: garbage bytes after "%PDF-" still parse.
  test("garbage bytes after %PDF- header still parse", async () => {
    const doc = await PdfDocument.load(enc(MIN.replace("%PDF-1.4", "%PDF-1.4\xa0sd")));
    expect(doc.getPageCount()).toBe(1);
  });

  // pypdf test_read_malformed_header (non-strict): a non-"%PDF-" header is
  // tolerated and the body is still recovered.
  test("non-%PDF- header is tolerated (lenient)", async () => {
    const doc = await PdfDocument.load(enc("foo" + MIN.slice(3)));
    expect(doc.getPageCount()).toBe(1);
  });

  // pypdf test_startxref_corrupt_trailing_pointer (#3238): a corrupt trailing
  // "startxref" keyword falls back to reconstructing the cross-reference table.
  test("corrupt trailing startxref keyword still recovers", async () => {
    const doc = await PdfDocument.load(enc(MIN.replace("startxref", "tartxref")));
    expect(doc.getPageCount()).toBe(1);
  });

  // pypdf test_read_malformed_body: "%PDF-" with no body raises (EOF marker not
  // found). better-pdf surfaces a PdfError rather than returning garbage.
  test("truncated body (header only) surfaces an error", async () => {
    // load() is lazy; the parse error surfaces when the document is first used.
    const doc = await PdfDocument.load(enc("%PDF-1.4\n"));
    expect(() => doc.getPageCount()).toThrow(PdfError);
  });
});

// ---------------------------------------------------------------------------
// Tier 5 — Real-world issue fixtures (downloaded from pypdf GitHub issues).
//   Fixtures under fixtures/pypdf/issues/ are the attachments referenced by the
//   named pypdf regression tests. See docs/pypdf-findings.md for the gaps these
//   surfaced in better-pdf (skipped tests below track them).
// ---------------------------------------------------------------------------
const iss = (name: string) => bytes(`issues/${name}`);
const loadIss = (name: string) => PdfDocument.load(iss(name));

describe("issue fixtures — forms (pypdf)", () => {
  // pypdf test_form_button__v_value_should_be_name_object (issue #3115): a set
  // button /V must serialize as a name object (/V /On), never a string (/V (/On)).
  test("iss3115: checked button serializes /V as a name object", async () => {
    const doc = await loadIss("iss3115-blank-form.pdf");
    expect(doc.getForm().getField("Other")?.states).toEqual(["On"]);
    doc.getForm().getCheckBox("Other").check();
    const raw = Buffer.from(await doc.save()).toString("latin1");
    expect(raw).toMatch(/\/V\s*\/On\b/);
    expect(raw).not.toMatch(/\/V\s*\(On\)/);
  });

  // pypdf test_i_in_choice_fields (issue #2611): setting a choice value must not
  // leave a stale selection index that overrides the displayed value.
  test("iss2611: dropdown selection round-trips (choice /I not stale)", async () => {
    const doc = await loadIss("iss2611-FRA.F.6180.150.pdf");
    expect(doc.getForm().getField("State")?.options).toContain("NY");
    doc.getForm().getDropdown("State").select("NY");
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getForm().getField("State")?.value).toBe("NY");
  });

  // pypdf test_field_box_upside_down (issue #2724): the widget's rectangle is
  // flipped (top < bottom). Filling it must still produce a valid appearance and
  // round-trip, not error out on the negative-height box.
  test("iss2724: filling a flipped-BBox text field round-trips", async () => {
    const doc = await loadIss("iss2724-FRA.F.6180.55.pdf");
    const w = doc.getForm().getField("FreightTrainMiles")?.widgets[0]!;
    expect(w.rect[1]).toBeGreaterThan(w.rect[3]); // confirm the box is flipped
    doc.getForm().getTextField("FreightTrainMiles").setText("0");
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getForm().getField("FreightTrainMiles")?.value).toBe("0");
  });

  // pypdf test_get_fields (tika-972486): a checkbox button exposes its on-state.
  // pypdf reports /_States_ == ["/On","/Off"]; better-pdf lists only the on-state
  // ("On"), with "Off" implicit.
  test("tika-972486: checkbox c1-1 exposes its on-state", async () => {
    const doc = await loadIss("tika-972486.pdf");
    expect(doc.getPageCount()).toBe(3);
    const fields = doc.getForm().getFields();
    expect(fields.length).toBeGreaterThan(100);
    const c1 = doc.getForm().getField("c1-1");
    expect(c1?.type).toBe("checkbox");
    expect(c1?.states).toEqual(["On"]);
  });

  // pypdf test_get_full_qualified_fields: a leaf text field reads its value.
  test("fields_with_dots: leaf text field reads its value", async () => {
    const doc = await loadIss("fields_with_dots.pdf");
    expect(doc.getForm().getField("other_field")?.value).toBe("Hello world!");
  });

  // pypdf test_get_full_qualified_fields (issue #2643 family): a parent field
  // with terminal kids is expanded into fully-qualified "parent.child" names,
  // and the terminal child is exposed as a real (typed) field, not the parent
  // as an "unknown".
  test("fields_with_dots: qualified child name customer.name is resolved", async () => {
    const doc = await loadIss("fields_with_dots.pdf");
    const fields = doc.getForm().getFields();
    const names = fields.map((f) => f.name);
    expect(names).toContain("customer.name");
    // The parent segment is not itself emitted as a field.
    expect(names).not.toContain("customer");
    expect(fields.find((f) => f.name === "customer.name")?.type).toBe("text");
  });

  // A hierarchical child can be filled by its qualified name and round-trips.
  test("fields_with_dots: qualified child name is fillable", async () => {
    const doc = await loadIss("fields_with_dots.pdf");
    doc.getForm().getTextField("customer.name").setText("Ada Lovelace");
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getForm().getField("customer.name")?.value).toBe("Ada Lovelace");
  });

  // Flattening a form with hierarchical fields removes them all — including the
  // nested children and their now-empty parents — leaving a field-free PDF.
  test("fields_with_dots: flatten clears the hierarchical fields", async () => {
    const doc = await loadIss("fields_with_dots.pdf");
    doc.getForm().flatten();
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getForm().getFields().length).toBe(0);
  });

  // pypdf test_looping_form (issue #2643): a deep/recursive field tree resolves
  // without looping, expanding into fully-qualified dotted descendants.
  test("iss2643: deep field tree resolves fully-qualified dotted names", async () => {
    const doc = await loadIss("iss2643-inheritance.pdf");
    expect(doc.getPageCount()).toBe(26);
    const names = doc.getForm().getFields().map((f) => f.name);
    // Flat top-level terminal fields survive...
    expect(names).toContain("DSS#3pg3#0hgu7");
    // ...and the "Text10" parent is expanded into qualified descendants rather
    // than surfacing the bare parent name.
    expect(names).not.toContain("Text10");
    expect(names.some((n) => n.startsWith("Text10."))).toBe(true);
  });

  // A field whose /DA names a standard-14 font that is absent from /DR is filled
  // by synthesizing that font into the appearance's /Resources/Font instead of
  // throwing (pypdf test_no_resource_for_14_std_fonts, issue #2670).
  test("iss2670: filling a std-14 /DA font absent from /DR", async () => {
    const doc = await loadIss("iss2670-f1040.pdf");
    const tf = doc.getForm().getFields().find((f) => f.type === "text")!;
    doc.getForm().getTextField(tf.name).setText("Brooks");
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getForm().getField(tf.name)?.value).toBe("Brooks");
  });
});

describe("issue fixtures — recovery (pypdf)", () => {
  // pypdf test_truncated_xref (issue #2575): a truncated xref table is rebuilt.
  test("iss2575: truncated xref rebuilds and pages are readable", async () => {
    const doc = await loadIss("iss2575-libreoffice-broken.pdf");
    expect(doc.getPageCount()).toBeGreaterThan(0);
    const out = await doc.save();
    expect((await PdfDocument.load(out)).getPageCount()).toBe(doc.getPageCount());
  });

  // pypdf test_corrupted_xref (issue #2516): the catalog's /Pages reference
  // points at the wrong object (the Info dict), so the strict parse yields zero
  // pages; recovery re-points /Pages at the real page-tree node.
  test("iss2516: corrupted /Pages reference recovers the page tree", async () => {
    const doc = await loadIss("iss2516.pdf");
    expect(doc.getPageCount()).toBeGreaterThan(0);
  });
});
