// Behavioral tests inspired by QPDF's test suite (https://github.com/qpdf/qpdf),
// adapted to the better-pdf API. QPDF is the reference implementation for PDF
// *structure* — xref reconstruction, incremental updates, object/xref streams,
// encryption R2–R6 and linearization — so it complements the pypdf (forms /
// recovery) and pdf-lib (generation) ported suites.
//
// Two kinds of tests live here:
//   * Tier 1 (structure/recovery) uses INLINE byte fixtures — hand-authored
//     malformed/edge-case PDFs that exercise the shapes QPDF's qtest suite
//     covers. These run everywhere, no external files.
//   * Tiers 2–3 (encryption / object streams) consume fixtures GENERATED by the
//     qpdf CLI via tests/scripts/gen-qpdf-fixtures.ts. They skip when those
//     fixtures are absent (qpdf is not installed on this machine).
//
// No QPDF source or fixture bytes are redistributed — see
// tests/fixtures/qpdf/LICENSE.qpdf for provenance. tests/qpdf-validate.test.ts
// separately uses qpdf as an *output validator* (the oracle direction).
import { describe, expect, test } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { PdfDocument } from "../src/index.ts";

const DIR = join(import.meta.dir, "fixtures/qpdf");
const enc = (s: string) => new TextEncoder().encode(s);
const bytes = (name: string) => new Uint8Array(readFileSync(join(DIR, name)));
const have = (name: string) => existsSync(join(DIR, name));

// ---------------------------------------------------------------------------
// Tier 1 — Structure & recovery (inline byte fixtures; QPDF qtest shapes)
//   QPDF's reader tolerates and repairs a wide range of structural damage while
//   honoring the spec's "later definition wins" rule for incremental updates.
// ---------------------------------------------------------------------------
describe("structure & recovery (qpdf reader semantics)", () => {
  // Well-formed baseline the other cases mutate.
  const MIN = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;

  test("baseline fixture loads (sanity)", async () => {
    const doc = await PdfDocument.load(enc(MIN));
    expect(doc.getPageCount()).toBe(1);
  });

  // QPDF honors incremental updates: an appended section redefining an object
  // (chained via the trailer's /Prev) supersedes the original. Here object 3's
  // MediaBox is enlarged from 200×200 to 400×400 by the appended section.
  test("incremental update: appended redefinition of a page wins", async () => {
    const INCR = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj
xref
0 4
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
190
%%EOF
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 400 400]>>endobj
xref
3 1
0000000300 00000 n
trailer<</Size 4/Root 1 0 R/Prev 190>>
startxref
370
%%EOF`;
    const p = (await PdfDocument.load(enc(INCR))).getPage(0);
    expect(p.width).toBe(400);
    expect(p.height).toBe(400);
  });

  // A chain of three xref sections (base + two appended updates). The newest
  // redefinition of the page must win across the whole /Prev chain.
  test("multi-section update chain: newest page definition wins", async () => {
    const CHAIN = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 100 100]>>endobj
trailer<</Size 4/Root 1 0 R>>
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 300]>>endobj
trailer<</Size 4/Root 1 0 R/Prev 0>>
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 700 700]>>endobj
trailer<</Size 4/Root 1 0 R/Prev 0>>
%%EOF`;
    const p = (await PdfDocument.load(enc(CHAIN))).getPage(0);
    expect(p.width).toBe(700);
  });

  // QPDF resolves an indirect /Length on a stream (a reference to a separate
  // integer object) rather than requiring it inline.
  test("indirect stream /Length is resolved", async () => {
    const INDIRECT = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R>>endobj
4 0 obj<</Length 5 0 R>>stream
BT /F1 12 Tf (hi) Tj ET
endstream endobj
5 0 obj 22 endobj
trailer<</Size 6/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(INDIRECT))).getPageCount()).toBe(1);
  });

  // No xref table at all — QPDF reconstructs the cross-reference by scanning
  // for `N G obj` tokens.
  test("missing xref table is reconstructed by object scan", async () => {
    const NOXREF = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(NOXREF))).getPageCount()).toBe(1);
  });

  // An xref table present but with all-zero (bogus) offsets forces the same
  // reconstruction path.
  test("bogus xref offsets are reconstructed", async () => {
    const BADOFF = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
xref
0 4
0000000000 65535 f
0000000000 00000 n
0000000000 00000 n
0000000000 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
190
%%EOF`;
    expect((await PdfDocument.load(enc(BADOFF))).getPageCount()).toBe(1);
  });

  // Two definitions of object 3 in one body (no reliable xref): on
  // reconstruction the later (highest-offset) definition wins.
  test("duplicate object number: last definition wins on reconstruct", async () => {
    const DUP = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 500 500]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    const p = (await PdfDocument.load(enc(DUP))).getPage(0);
    expect(p.width).toBe(500);
  });

  // An understated trailer /Size must not hide objects numbered beyond it.
  test("understated trailer /Size still resolves all objects", async () => {
    const BADSIZE = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 2/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(BADSIZE))).getPageCount()).toBe(1);
  });

  // Junk bytes before the %PDF- header (QPDF seeks the header and adjusts all
  // offsets accordingly).
  test("leading junk before %PDF- header is tolerated", async () => {
    const JUNK = `GARBAGE GARBAGE GARBAGE
%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(JUNK))).getPageCount()).toBe(1);
  });

  // Comments interleaved in the body must be skipped by the tokenizer.
  test("comments in the body are tolerated", async () => {
    const COMMENTS = `%PDF-1.4
%¥±
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
% a comment inside the body
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(COMMENTS))).getPageCount()).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Tier 2 — Encryption matrix (fixtures generated by qpdf --encrypt)
//   Run tests/scripts/gen-qpdf-fixtures.ts on a machine with qpdf to populate
//   fixtures/qpdf/encryption/. These tests skip until then.
// ---------------------------------------------------------------------------
const encReady = have("encryption/r6-both-passwords.pdf");
describe.skipIf(!encReady)("encryption matrix (qpdf --encrypt)", () => {
  const cases: Array<{ file: string; password: string; note: string }> = [
    { file: "r2-rc4-40-empty.pdf", password: "", note: "R2 RC4-40, empty" },
    { file: "r3-rc4-128-empty.pdf", password: "", note: "R3 RC4-128, empty" },
    { file: "r6-aes-256-empty.pdf", password: "", note: "R6 AES-256, empty" },
    { file: "r2-rc4-40-user.pdf", password: "asdfzxcv", note: "R2 RC4-40 user pw" },
    { file: "r4-aes-128-user.pdf", password: "asdfzxcv", note: "R4 AES-128 user pw" },
  ];
  for (const { file, password, note } of cases) {
    test(`decrypts ${file} (${note})`, async () => {
      const doc = await PdfDocument.load(bytes(`encryption/${file}`), { password });
      expect(doc.getPageCount()).toBe(1);
    });
  }

  test("all encryption fixtures report isEncrypted; plaintext base does not", async () => {
    for (const { file } of cases) {
      expect(await PdfDocument.isEncrypted(bytes(`encryption/${file}`))).toBe(true);
    }
    expect(await PdfDocument.isEncrypted(bytes("base.pdf"))).toBe(false);
  });

  // r6-both-passwords.pdf has user="foo", owner="bar": distinguish the roles and
  // reject a wrong password (empty-owner files would open as owner for any input).
  test("passwordType distinguishes owner, user, and wrong password", async () => {
    const both = bytes("encryption/r6-both-passwords.pdf");
    expect(await PdfDocument.passwordType(both, "bar")).toBe("owner");
    expect(await PdfDocument.passwordType(both, "foo")).toBe("user");
    expect(await PdfDocument.passwordType(both, "nope")).toBe(null);
  });
});

// ---------------------------------------------------------------------------
// Tier 3 — Object/xref streams & linearization (qpdf-generated)
//   PDF-1.5+ compressed object streams + cross-reference streams, and a
//   linearized ("web-optimized") layout, both emitted by qpdf.
// ---------------------------------------------------------------------------
const structReady = have("structure/object-streams.pdf");
describe.skipIf(!structReady)("object streams & linearization (qpdf-produced)", () => {
  test("object-stream / xref-stream file loads and round-trips", async () => {
    const doc = await PdfDocument.load(bytes("structure/object-streams.pdf"));
    expect(doc.getPageCount()).toBe(1);
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getPageCount()).toBe(1);
  });

  test("linearized file loads and round-trips", async () => {
    const doc = await PdfDocument.load(bytes("structure/linearized.pdf"));
    expect(doc.getPageCount()).toBe(1);
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getPageCount()).toBe(1);
  });
});
