// Behavioral tests inspired by QPDF's test suite (https://github.com/qpdf/qpdf),
// adapted to the better-pdf API. QPDF is the reference implementation for PDF
// *structure* — xref reconstruction, incremental updates, object/xref streams,
// encryption R2–R6 and linearization — so it complements the pypdf (forms /
// recovery) and pdf-lib (generation) ported suites.
//
// Two kinds of tests live here:
//   * Tier 1 (structure/recovery) uses INLINE byte fixtures — hand-authored
//     malformed/edge-case PDFs that exercise the shapes QPDF's qtest suite
//     covers. These run everywhere, no external files.
//   * Tiers 2–3 (encryption / object streams) consume fixtures GENERATED by the
//     qpdf CLI via tests/scripts/gen-qpdf-fixtures.ts. They skip when those
//     fixtures are absent (qpdf is not installed on this machine).
//
// No QPDF source or fixture bytes are redistributed — see
// tests/fixtures/qpdf/LICENSE.qpdf for provenance. tests/qpdf-validate.test.ts
// separately uses qpdf as an *output validator* (the oracle direction).
import { describe, expect, test } from "bun:test";
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { PdfDocument } from "../src/index.ts";

const DIR = join(import.meta.dir, "fixtures/qpdf");
const enc = (s: string) => new TextEncoder().encode(s);
const bytes = (name: string) => new Uint8Array(readFileSync(join(DIR, name)));
const have = (name: string) => existsSync(join(DIR, name));

// ---------------------------------------------------------------------------
// Tier 1 — Structure & recovery (inline byte fixtures; QPDF qtest shapes)
//   QPDF's reader tolerates and repairs a wide range of structural damage while
//   honoring the spec's "later definition wins" rule for incremental updates.
// ---------------------------------------------------------------------------
describe("structure & recovery (qpdf reader semantics)", () => {
  // Well-formed baseline the other cases mutate.
  const MIN = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;

  test("baseline fixture loads (sanity)", async () => {
    const doc = await PdfDocument.load(enc(MIN));
    expect(doc.getPageCount()).toBe(1);
  });

  // QPDF honors incremental updates: an appended section redefining an object
  // (chained via the trailer's /Prev) supersedes the original. Here object 3's
  // MediaBox is enlarged from 200×200 to 400×400 by the appended section.
  test("incremental update: appended redefinition of a page wins", async () => {
    const INCR = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj
xref
0 4
0000000000 65535 f
0000000009 00000 n
0000000058 00000 n
0000000115 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
190
%%EOF
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 400 400]>>endobj
xref
3 1
0000000300 00000 n
trailer<</Size 4/Root 1 0 R/Prev 190>>
startxref
370
%%EOF`;
    const p = (await PdfDocument.load(enc(INCR))).getPage(0);
    expect(p.width).toBe(400);
    expect(p.height).toBe(400);
  });

  // A chain of three xref sections (base + two appended updates). The newest
  // redefinition of the page must win across the whole /Prev chain.
  test("multi-section update chain: newest page definition wins", async () => {
    const CHAIN = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 100 100]>>endobj
trailer<</Size 4/Root 1 0 R>>
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 300 300]>>endobj
trailer<</Size 4/Root 1 0 R/Prev 0>>
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 700 700]>>endobj
trailer<</Size 4/Root 1 0 R/Prev 0>>
%%EOF`;
    const p = (await PdfDocument.load(enc(CHAIN))).getPage(0);
    expect(p.width).toBe(700);
  });

  // QPDF resolves an indirect /Length on a stream (a reference to a separate
  // integer object) rather than requiring it inline.
  test("indirect stream /Length is resolved", async () => {
    const INDIRECT = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]/Contents 4 0 R>>endobj
4 0 obj<</Length 5 0 R>>stream
BT /F1 12 Tf (hi) Tj ET
endstream endobj
5 0 obj 22 endobj
trailer<</Size 6/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(INDIRECT))).getPageCount()).toBe(1);
  });

  // No xref table at all — QPDF reconstructs the cross-reference by scanning
  // for `N G obj` tokens.
  test("missing xref table is reconstructed by object scan", async () => {
    const NOXREF = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(NOXREF))).getPageCount()).toBe(1);
  });

  // An xref table present but with all-zero (bogus) offsets forces the same
  // reconstruction path.
  test("bogus xref offsets are reconstructed", async () => {
    const BADOFF = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
xref
0 4
0000000000 65535 f
0000000000 00000 n
0000000000 00000 n
0000000000 00000 n
trailer<</Size 4/Root 1 0 R>>
startxref
190
%%EOF`;
    expect((await PdfDocument.load(enc(BADOFF))).getPageCount()).toBe(1);
  });

  // Two definitions of object 3 in one body (no reliable xref): on
  // reconstruction the later (highest-offset) definition wins.
  test("duplicate object number: last definition wins on reconstruct", async () => {
    const DUP = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 200 200]>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 500 500]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    const p = (await PdfDocument.load(enc(DUP))).getPage(0);
    expect(p.width).toBe(500);
  });

  // An understated trailer /Size must not hide objects numbered beyond it.
  test("understated trailer /Size still resolves all objects", async () => {
    const BADSIZE = `%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 2/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(BADSIZE))).getPageCount()).toBe(1);
  });

  // Junk bytes before the %PDF- header (QPDF seeks the header and adjusts all
  // offsets accordingly).
  test("leading junk before %PDF- header is tolerated", async () => {
    const JUNK = `GARBAGE GARBAGE GARBAGE
%PDF-1.4
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(JUNK))).getPageCount()).toBe(1);
  });

  // Comments interleaved in the body must be skipped by the tokenizer.
  test("comments in the body are tolerated", async () => {
    const COMMENTS = `%PDF-1.4
%¥±
1 0 obj<</Type/Catalog/Pages 2 0 R>>endobj
% a comment inside the body
2 0 obj<</Type/Pages/Kids[3 0 R]/Count 1>>endobj
3 0 obj<</Type/Page/Parent 2 0 R/MediaBox[0 0 612 792]>>endobj
trailer<</Size 4/Root 1 0 R>>
%%EOF`;
    expect((await PdfDocument.load(enc(COMMENTS))).getPageCount()).toBe(1);
  });
});

// ---------------------------------------------------------------------------
// Tier 2 — Encryption matrix (fixtures generated by qpdf --encrypt)
//   Run tests/scripts/gen-qpdf-fixtures.ts on a machine with qpdf to populate
//   fixtures/qpdf/encryption/. These tests skip until then.
// ---------------------------------------------------------------------------
const encReady = have("encryption/r6-both-passwords.pdf");
describe.skipIf(!encReady)("encryption matrix (qpdf --encrypt)", () => {
  const cases: Array<{ file: string; password: string; note: string }> = [
    { file: "r2-rc4-40-empty.pdf", password: "", note: "R2 RC4-40, empty" },
    { file: "r3-rc4-128-empty.pdf", password: "", note: "R3 RC4-128, empty" },
    { file: "r6-aes-256-empty.pdf", password: "", note: "R6 AES-256, empty" },
    { file: "r2-rc4-40-user.pdf", password: "asdfzxcv", note: "R2 RC4-40 user pw" },
    { file: "r4-aes-128-user.pdf", password: "asdfzxcv", note: "R4 AES-128 user pw" },
  ];
  for (const { file, password, note } of cases) {
    test(`decrypts ${file} (${note})`, async () => {
      const doc = await PdfDocument.load(bytes(`encryption/${file}`), { password });
      expect(doc.getPageCount()).toBe(1);
    });
  }

  test("all encryption fixtures report isEncrypted; plaintext base does not", async () => {
    for (const { file } of cases) {
      expect(await PdfDocument.isEncrypted(bytes(`encryption/${file}`))).toBe(true);
    }
    expect(await PdfDocument.isEncrypted(bytes("base.pdf"))).toBe(false);
  });

  // r6-both-passwords.pdf has user="foo", owner="bar": distinguish the roles and
  // reject a wrong password (empty-owner files would open as owner for any input).
  test("passwordType distinguishes owner, user, and wrong password", async () => {
    const both = bytes("encryption/r6-both-passwords.pdf");
    expect(await PdfDocument.passwordType(both, "bar")).toBe("owner");
    expect(await PdfDocument.passwordType(both, "foo")).toBe("user");
    expect(await PdfDocument.passwordType(both, "nope")).toBe(null);
  });

  // Regression: files whose trailer is a cross-reference *stream* (no `trailer`
  // keyword at all) once reported passwordType null for every password — the
  // same answer as a wrong password — while load() decrypted them fine.
  // The user-password fixtures were written with an empty owner password, which
  // qpdf fills in with the user password — so that password authenticates as
  // owner (the superset), exactly as it does for their classic-trailer twins.
  const xrefStm: Array<{ file: string; password: string; expected: "user" | "owner" }> = [
    { file: "r2-rc4-40-user-xrefstm.pdf", password: "asdfzxcv", expected: "owner" },
    { file: "r3-rc4-128-user-xrefstm.pdf", password: "asdfzxcv", expected: "owner" },
    { file: "r6-both-passwords-xrefstm.pdf", password: "foo", expected: "user" },
    { file: "r6-both-passwords-xrefstm.pdf", password: "bar", expected: "owner" },
  ];
  for (const { file, password, expected } of xrefStm) {
    test(`passwordType classifies ${file} with "${password}" as ${expected}`, async () => {
      const data = bytes(`encryption/${file}`);
      // Guard the premise: this fixture really has no classic trailer.
      expect(new TextDecoder("latin1").decode(data)).not.toContain("trailer");
      expect(await PdfDocument.passwordType(data, password)).toBe(expected);
      expect((await PdfDocument.load(data, { password })).getPageCount()).toBe(1);
    });
  }

  // Structure must not change the answer: each xref-stream fixture has a
  // classic-trailer twin encrypted with the same passwords.
  test("xref-stream files classify identically to their classic-trailer twins", async () => {
    const twins: Array<[string, string, string[]]> = [
      ["r2-rc4-40-user.pdf", "r2-rc4-40-user-xrefstm.pdf", ["asdfzxcv", "nope"]],
      ["r6-both-passwords.pdf", "r6-both-passwords-xrefstm.pdf", ["foo", "bar", "nope"]],
    ];
    for (const [classic, xref, passwords] of twins) {
      for (const password of passwords) {
        expect({
          password,
          type: await PdfDocument.passwordType(bytes(`encryption/${xref}`), password),
        }).toEqual({
          password,
          type: await PdfDocument.passwordType(bytes(`encryption/${classic}`), password),
        });
      }
    }
  });

  // Known limitation, pinned so it stays visible: lopdf SASLprep-normalizes R6
  // passwords with no raw-bytes load path, so a file qpdf keyed off the raw NFD
  // bytes of "café" cannot be opened with any spelling of that password. The
  // owner password (plain ASCII) still works, and — the part that matters —
  // passwordType and load agree. See docs/lopdf-saslprep-issue.md.
  const NFD = "cafe\u0301"; // "café" with a combining acute
  for (const file of ["r6-nfd-password.pdf", "r6-nfd-password-xrefstm.pdf"]) {
    test(`non-normalized Unicode password is rejected consistently (${file})`, async () => {
      const data = bytes(`encryption/${file}`);
      for (const password of [NFD, "caf\u00e9"]) {
        expect(await PdfDocument.passwordType(data, password)).toBe(null);
        await expect(PdfDocument.load(data, { password })).rejects.toThrow();
      }
      // The ASCII owner password of the same file opens it normally.
      expect(await PdfDocument.passwordType(data, "owner")).toBe("owner");
      expect((await PdfDocument.load(data, { password: "owner" })).getPageCount()).toBe(1);
    });
  }

  // An encrypted file whose xref is damaged must still be refused as encrypted:
  // the recovery loader rebuilds a fresh trailer, so if the encryption gate
  // misses the /Encrypt declaration the file "loads" with no password at all,
  // its strings and streams still ciphertext. The declaration sits inside the
  // xref stream object here, where a trailer-only scan cannot see it.
  test("damaged encrypted xref-stream file is refused, not silently repaired", async () => {
    const original = bytes("encryption/r3-rc4-128-user-xrefstm.pdf");
    const broken = new Uint8Array(original);
    const at = new TextDecoder("latin1").decode(original).lastIndexOf("startxref");
    broken.fill(0x78, at, at + "startxref".length); // clobber → strict parse fails
    expect(await PdfDocument.isEncrypted(broken)).toBe(true);
    // `load` is lazy — parsing happens on first use, so the refusal surfaces
    // there rather than from the load call itself.
    const doc = await PdfDocument.load(broken);
    expect(() => doc.getPageCount()).toThrow(/encrypted/i);
    // The intact file is unaffected.
    expect((await PdfDocument.load(original, { password: "asdfzxcv" })).getPageCount()).toBe(1);
  });

  test("passwordType and load agree on every encryption fixture", async () => {
    // The invariant callers depend on: a non-null passwordType means the
    // password opens the file, and null means it does not. Anything else makes
    // a caller that gates on passwordType reject valid passwords (or accept
    // invalid ones).
    const all: Array<[string, string]> = [
      ...cases.map(({ file, password }) => [file, password] as [string, string]),
      ...xrefStm.map(({ file, password }) => [file, password] as [string, string]),
      ["r6-both-passwords.pdf", "nope"],
      ["r6-both-passwords-xrefstm.pdf", "nope"],
    ];
    for (const [file, password] of all) {
      const data = bytes(`encryption/${file}`);
      const classified = (await PdfDocument.passwordType(data, password)) !== null;
      const opens = await PdfDocument.load(data, { password }).then(
        () => true,
        () => false,
      );
      expect({ file, password, classified }).toEqual({ file, password, classified: opens });
    }
  });
});

// ---------------------------------------------------------------------------
// Tier 3 — Object/xref streams & linearization (qpdf-generated)
//   PDF-1.5+ compressed object streams + cross-reference streams, and a
//   linearized ("web-optimized") layout, both emitted by qpdf.
// ---------------------------------------------------------------------------
const structReady = have("structure/object-streams.pdf");
describe.skipIf(!structReady)("object streams & linearization (qpdf-produced)", () => {
  test("object-stream / xref-stream file loads and round-trips", async () => {
    const doc = await PdfDocument.load(bytes("structure/object-streams.pdf"));
    expect(doc.getPageCount()).toBe(1);
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getPageCount()).toBe(1);
  });

  test("linearized file loads and round-trips", async () => {
    const doc = await PdfDocument.load(bytes("structure/linearized.pdf"));
    expect(doc.getPageCount()).toBe(1);
    const reloaded = await PdfDocument.load(await doc.save());
    expect(reloaded.getPageCount()).toBe(1);
  });
});
