import type { FieldInfo, FieldType } from "./form.js";

export interface GenerateFormTypesOptions {
  /**
   * Prefix for generated type and value names. Must be a valid TypeScript
   * identifier; defaults to `BetterPdfForm`.
   */
  typeName?: string;
}

const TYPE_SUFFIXES: Record<FieldType, string> = {
  text: "Text",
  checkbox: "CheckBox",
  radio: "RadioGroup",
  dropdown: "Dropdown",
  listbox: "ListBox",
  signature: "Signature",
  pushbutton: "PushButton",
  unknown: "Unknown",
};

/**
 * Generate a TypeScript module that describes the fields in a PDF form.
 *
 * The generated module exports a metadata object and field-name helper types.
 * Pass the metadata object to `doc.getForm<typeof metadata>()` to get
 * compile-time checks for field names, field kinds, and choice values.
 *
 * @param fields - Field metadata, usually from `doc.getForm().getFields()`.
 * @param options - Naming options for the generated TypeScript module.
 * @returns TypeScript source code.
 *
 * @example
 * ```ts
 * import { PdfDocument, generateFormTypes } from "@ignaciano3/better-pdf";
 *
 * const doc = await PdfDocument.load(pdfBytes);
 * const source = generateFormTypes(doc.getForm().getFields(), {
 *   typeName: "EnrollmentForm",
 * });
 *
 * await Bun.write("src/enrollment-form-types.ts", source);
 * ```
 *
 * @example
 * ```ts
 * import { enrollmentFormFields } from "./enrollment-form-types.js";
 *
 * const form = doc.getForm<typeof enrollmentFormFields>();
 * form.getDropdown("beneficiario.estado_civil").select("Casado");
 * ```
 */
export function generateFormTypes(
  fields: readonly FieldInfo[],
  options: GenerateFormTypesOptions = {},
): string {
  const typeName = options.typeName ?? "BetterPdfForm";
  assertIdentifier(typeName, "typeName");

  const sorted = [...fields].sort((a, b) => a.name.localeCompare(b.name));
  const names = sorted.map((field) => field.name);
  const metadataName = lowerFirst(typeName) + "Fields";
  const fieldMapName = `${typeName}Fields`;
  const fieldNameType = `${typeName}FieldName`;
  const byTypeName = `${typeName}FieldNameByType`;
  const choiceName = `${typeName}ChoiceFieldName`;

  const lines: string[] = [
    "/* eslint-disable */",
    "/* Generated by better-pdf. Do not edit by hand. */",
    `/* Usage: const form = doc.getForm<typeof ${metadataName}>(); */`,
    "",
    `export const ${metadataName} = {`,
  ];

  for (const field of sorted) {
    // Schema-only emission: the metadata object exists so TypeScript can
    // narrow field names, accessors, and choice values. Field *data* (values,
    // flags, appearance) is deliberately omitted so generating from a filled
    // form never bakes answers — potentially PII — into source control.
    lines.push(`  ${quote(field.name)}: {`);
    lines.push(`    type: ${quote(field.type)},`);
    lines.push(`    readOnly: ${field.readOnly ? "true" : "false"},`);
    lines.push(`    states: ${readonlyTuple(field.states)},`);
    lines.push(`    options: ${readonlyTuple(field.options)},`);
    lines.push(`    multiSelect: ${field.multiSelect ? "true" : "false"},`);
    lines.push("  },");
  }

  lines.push("} as const;");
  lines.push("");
  lines.push(`export type ${fieldNameType} = ${literalUnion(names)};`);
  lines.push(`export type ${fieldMapName} = typeof ${metadataName};`);
  // The full field-type union (not just the types present in this form), so the
  // per-type name aliases below always satisfy the constraint and resolve to
  // `never` for types this form happens not to use.
  lines.push(`export type ${typeName}FieldType = ${literalUnion(Object.keys(TYPE_SUFFIXES))};`);
  lines.push(`export type ${byTypeName}<TType extends ${typeName}FieldType> = {`);
  lines.push(
    `  [TName in ${fieldNameType}]: ${fieldMapName}[TName]["type"] extends TType ? TName : never;`,
  );
  lines.push(`}[${fieldNameType}];`);
  lines.push("");

  for (const [type, suffix] of Object.entries(TYPE_SUFFIXES) as [FieldType, string][]) {
    lines.push(`export type ${typeName}${suffix}FieldName = ${byTypeName}<${quote(type)}>;`);
  }

  lines.push("");
  lines.push(
    `export type ${choiceName} = ${typeName}RadioGroupFieldName | ${typeName}DropdownFieldName | ${typeName}ListBoxFieldName;`,
  );
  lines.push(
    `export type ${typeName}Options<TName extends ${choiceName}> = ${fieldMapName}[TName]["options"][number] | ${fieldMapName}[TName]["states"][number];`,
  );
  lines.push("");

  return lines.join("\n");
}

function assertIdentifier(value: string, label: string): void {
  if (!/^[$A-Z_a-z][$\w]*$/.test(value)) {
    throw new Error(`${label} must be a valid TypeScript identifier`);
  }
}

function lowerFirst(value: string): string {
  return value.slice(0, 1).toLowerCase() + value.slice(1);
}

function literalUnion(values: readonly string[]): string {
  if (values.length === 0) return "never";
  return values.map(quote).join(" | ");
}

function readonlyTuple(values: readonly string[]): string {
  if (values.length === 0) return "[] as const";
  return `[${values.map(quote).join(", ")}] as const`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}
