// Generates crates/core/src/font_metrics.rs from the Adobe Core 14 AFM data
// shipped in @pdf-lib/standard-fonts: WinAnsi advance-width tables for the 12
// standard text fonts, plus a unicode->WinAnsi-byte map for encoding.
// Run with `bun run generate:font-metrics`; the output is committed.
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { Font, FontNames, Encodings } from "@pdf-lib/standard-fonts";

const FONTS: FontNames[] = [
  FontNames.Courier, FontNames.CourierBold, FontNames.CourierOblique, FontNames.CourierBoldOblique,
  FontNames.Helvetica, FontNames.HelveticaBold, FontNames.HelveticaOblique, FontNames.HelveticaBoldOblique,
  FontNames.TimesRoman, FontNames.TimesRomanBold, FontNames.TimesRomanItalic, FontNames.TimesRomanBoldItalic,
];

// WinAnsi code (32..=255) -> glyph name.
const codeToName = new Map<number, string>();
// unicode codepoint -> WinAnsi byte, for codepoints >= 0x80 (ASCII is identity).
const fromUnicode: [number, number][] = [];
for (const cp of Encodings.WinAnsi.supportedCodePoints) {
  const { code, name } = Encodings.WinAnsi.encodeUnicodeCodePoint(cp);
  if (code >= 32 && code <= 255 && !codeToName.has(code)) codeToName.set(code, name);
  if (cp >= 0x80 && code >= 32 && code <= 255) fromUnicode.push([cp, code]);
}
fromUnicode.sort((a, b) => a[0] - b[0]);

const lines: string[] = [
  "//! GENERATED by scripts/gen-font-metrics.ts - do not edit by hand.",
  "//! WinAnsi advance widths (units/1000 em) for the standard-14 text fonts,",
  "//! indexed by `code - 32` for codes 32..=255 (0 = glyph not in the font),",
  "//! from the Adobe Core 14 AFM data in @pdf-lib/standard-fonts.",
  "",
];

for (const fontName of FONTS) {
  const font = Font.load(fontName);
  const widths: number[] = [];
  for (let code = 32; code <= 255; code++) {
    const glyph = codeToName.get(code);
    const w = glyph ? font.getWidthOfGlyph(glyph) : undefined;
    widths.push(typeof w === "number" ? Math.round(w) : 0);
  }
  const ident = (fontName as string).toUpperCase().replace(/-/g, "_");
  lines.push(`pub(crate) static ${ident}: [u16; 224] = [`);
  for (let i = 0; i < widths.length; i += 16) {
    lines.push(`    ${widths.slice(i, i + 16).join(", ")},`);
  }
  lines.push("];", "");
}

lines.push("/// (unicode codepoint, WinAnsi byte) pairs for codepoints >= 0x80, sorted");
lines.push("/// by codepoint for binary search. ASCII (< 0x80) is an identity mapping.");
lines.push("pub(crate) static WINANSI_FROM_UNICODE: &[(u32, u8)] = &[");
for (let i = 0; i < fromUnicode.length; i += 8) {
  lines.push(
    "    " + fromUnicode.slice(i, i + 8).map(([cp, b]) => `(${cp}, ${b})`).join(", ") + ",",
  );
}
lines.push("];", "");

const out = join(import.meta.dir, "../crates/core/src/font_metrics.rs");
writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out} (${FONTS.length} fonts, ${fromUnicode.length} encoding pairs)`);
