import type { FieldInfo, FieldType } from "./form.js";

export interface GenerateFormTypesOptions {
  /**
   * Prefix for generated type and value names. Must be a valid TypeScript
   * identifier; defaults to `BetterPdfForm`.
   */
  typeName?: string;
}

const TYPE_SUFFIXES: Record<FieldType, string> = {
  text: "Text",
  checkbox: "CheckBox",
  radio: "RadioGroup",
  dropdown: "Dropdown",
  listbox: "ListBox",
  signature: "Signature",
  pushbutton: "PushButton",
  unknown: "Unknown",
};

export function generateFormTypes(
  fields: readonly FieldInfo[],
  options: GenerateFormTypesOptions = {},
): string {
  const typeName = options.typeName ?? "BetterPdfForm";
  assertIdentifier(typeName, "typeName");

  const sorted = [...fields].sort((a, b) => a.name.localeCompare(b.name));
  const names = sorted.map((field) => field.name);
  const metadataName = lowerFirst(typeName) + "Fields";
  const fieldMapName = `${typeName}Fields`;
  const fieldNameType = `${typeName}FieldName`;
  const byTypeName = `${typeName}FieldNameByType`;
  const choiceName = `${typeName}ChoiceFieldName`;

  const lines: string[] = [
    "/* eslint-disable */",
    "/* Generated by better-pdf. Do not edit by hand. */",
    "",
    `export const ${metadataName} = {`,
  ];

  for (const field of sorted) {
    lines.push(`  ${quote(field.name)}: {`);
    lines.push(`    type: ${quote(field.type)},`);
    lines.push(`    readOnly: ${field.readOnly ? "true" : "false"},`);
    lines.push(`    value: ${field.value === null ? "null" : quote(field.value)},`);
    lines.push(`    states: ${readonlyTuple(field.states)},`);
    lines.push(`    options: ${readonlyTuple(field.options)},`);
    lines.push("  },");
  }

  lines.push("} as const;");
  lines.push("");
  lines.push(`export type ${fieldNameType} = ${literalUnion(names)};`);
  lines.push(`export type ${fieldMapName} = typeof ${metadataName};`);
  lines.push(`export type ${typeName}FieldType = ${fieldMapName}[keyof ${fieldMapName}]["type"];`);
  lines.push(`export type ${byTypeName}<TType extends ${typeName}FieldType> = {`);
  lines.push(
    `  [TName in ${fieldNameType}]: ${fieldMapName}[TName]["type"] extends TType ? TName : never;`,
  );
  lines.push(`}[${fieldNameType}];`);
  lines.push("");

  for (const [type, suffix] of Object.entries(TYPE_SUFFIXES) as [FieldType, string][]) {
    lines.push(`export type ${typeName}${suffix}FieldName = ${byTypeName}<${quote(type)}>;`);
  }

  lines.push("");
  lines.push(
    `export type ${choiceName} = ${typeName}RadioGroupFieldName | ${typeName}DropdownFieldName | ${typeName}ListBoxFieldName;`,
  );
  lines.push(
    `export type ${typeName}Options<TName extends ${choiceName}> = ${fieldMapName}[TName]["options"][number] | ${fieldMapName}[TName]["states"][number];`,
  );
  lines.push("");

  return lines.join("\n");
}

function assertIdentifier(value: string, label: string): void {
  if (!/^[$A-Z_a-z][$\w]*$/.test(value)) {
    throw new Error(`${label} must be a valid TypeScript identifier`);
  }
}

function lowerFirst(value: string): string {
  return value.slice(0, 1).toLowerCase() + value.slice(1);
}

function literalUnion(values: readonly string[]): string {
  if (values.length === 0) return "never";
  return values.map(quote).join(" | ");
}

function readonlyTuple(values: readonly string[]): string {
  if (values.length === 0) return "[] as const";
  return `[${values.map(quote).join(", ")}] as const`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}
